name: example
description: Demonstrates how to use the jpush plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  cupertino_icons: ^0.1.2
  fl_jpush:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
