name: example
description: Demonstrates how to use the jpush plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  fl_jpush:
    path: ../
  flutter:
    sdk: flutter
  flutter_curiosity: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
